    - &OrgNUM_OF_ORG
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: OrgNUM_OF_ORGMSP

        # ID to load the MSP definition as
        ID: OrgNUM_OF_ORGMSP

        MSPDir: crypto-config/peerOrganizations/orgNUM_OF_ORG.example.com/msp

        # Policies defines the set of policies at this level of the config tree
        # For organization policies, their canonical path is usually
        #   /Channel/<Application|Orderer>/<OrgName>/<PolicyName>
        Policies:
            Readers:
                Type: Signature
                Rule: "OR('OrgNUM_OF_ORGMSP.admin', 'OrgNUM_OF_ORGMSP.peer', 'OrgNUM_OF_ORGMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('OrgNUM_OF_ORGMSP.admin', 'OrgNUM_OF_ORGMSP.client', 'OrgNUM_OF_ORGMSP.peer')"
            Admins:
                Type: Signature
                Rule: "OR('OrgNUM_OF_ORGMSP.admin')"

        # leave this flag set to true.
        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.orgNUM_OF_ORG.example.com
              Port: 7051

